apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yaml convert --volumes hostPath
    kompose.service.type: nodeport
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  ports:
  - name: "32000"
    port: 32000
    targetPort: 3306
  selector:
    io.kompose.service: db
  type: NodePort
status:
  loadBalancer: {}
