version: "2"
services:
  app:
   # build: ./app
    image: jperitz/favorite-colors:latest
    links:
      - db
    ports:
      - "5000:5000"
    labels:
      kompose.service.type: nodeport

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    labels:
      kompose.service.type: nodeport
